export const GET_INGREDIENTS_CONSTRUCTOR: "GET_INGREDIENTS_CONSTRUCTOR" =
    "GET_INGREDIENTS_CONSTRUCTOR";
export const ADD_INGREDIENTS_CONSTRUCTOR: "ADD_INGREDIENTS_CONSTRUCTOR" =
    "ADD_INGREDIENTS_CONSTRUCTOR";
export const DELETE_INGREDIENTS_CONSTRUCTOR: "DELETE_INGREDIENTS_CONSTRUCTOR" =
    "DELETE_INGREDIENTS_CONSTRUCTOR";
export const MOVE_INGREDIENTS_CONSTRUCTOR: "MOVE_INGREDIENTS_CONSTRUCTOR" =
    "MOVE_INGREDIENTS_CONSTRUCTOR";

export const ADD_DATA_INGREDIENTS_MODAL: "ADD_DATA_INGREDIENTS_MODAL" =
    "ADD_DATA_INGREDIENTS_MODAL";
export const DELETE_DATA_INGREDIENTS_MODAL: "DELETE_DATA_INGREDIENTS_MODAL" =
    "DELETE_DATA_INGREDIENTS_MODAL";
